name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Build & Publish Docker Image

    runs-on: ubuntu-latest

    steps:
      # Récupération du dépôt
      - name: Checkout
        uses: actions/checkout@v4

      # Installation de Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # Dépendances
      - name: Install dependencies
        run: npm ci

      # Vérifications qualité
      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run type-check

      # Vérifie que le projet compile
      - name: Build Next.js
        run: npm run build

      ################################################
      # Docker
      #################################################

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: fayemameibra/devops-portfolio:v0.0.2

      # - name: Extract Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: mameibrafaye/devops-portfolio
      #     tags: |
      #       type=raw,value=latest
      #       type=sha

      # - name: Build and Push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
